### PR TITLE
Save state of instance popup "Save" button and set as default while popup is in use.

### PR DESCRIPTION
**Pull request by eyl407**
The Instance Table popup default is currently "Save & Continue".   

Change the default popup save button to "Save & Next Instance".   Change the default popup save button to the last used popup save button as long as instance popup has not been closed.

### CODE REVIEW

**Comment by eyl407** [comment]
Added image preview when attachments are displayed in instance table.  Support jpg, gif, bmp, tiff, pdf and dcm file formats.

**Review by lsgs — COMMENTED** [review]
Sorry @eyl407 but I'm struggling a bit with this. What is it you actually changed? The bit with `UIState::saveUIStateValue()`? What are those js files?

**Comment by eyl407** [comment]
Sorry for the long hiatus @lsgs.  I missed your previous comment a while back.  There are multiple updates in this pull request now.
1.  Saves the last button used by the user in the popup window and sets that as the default for the next popup window  (that's the reason for UIState::saveUIStateValue())
2. Adds image thumbnails to the instance table for columns that may contain image attachments.  Supported image types include jpeg, gif, tiff, png, pdf and dcm (dicoms).  This is the reason for the inclusion of the js files.
3. Fixes "Save & Next Instance" button behavior to ensure that the next instance displayed belongs to the same parent record/instance.  Otherwise, the next instance displayed might belong to a different parent record which users found confusing.
4. Added "Save & New Instance" button to the popup form if the user has permissions.  This is just for convenience so the user doesn't have to close the popup and then open a new one.

**Comment by lsgs** [comment]
Hello @eyl407. I've submitted a new version with various updates and fixes, including for the issue with the save button state, which actually turned out to be a much simpler thing! :) So 1, 3, and 4 should be good in the new version now, I think.

Apologies, but I have not included the image thumbnail functionality in the new version. There are too many conflicts for me to comfortably merge the files and test in the time that I have. I am definitely open to including the functionality, but please can you refresh again from master and see whether you can achieve it without including any new libraries? Can it be done using REDCap's built-in image and PDF display functions?

**Pull request closed without merging**
